## Makefile for running iscam
## Targets: 
##		all:   -clean the directory, produce .tex and .pdf files


all:
	latexmk ICCAT.tex -pdf



clean: 
	rm *.bbl
	rm *.blg
	rm *.aux
	rm *.log
	rm ICCAT.pdf

